# Generated by Django 4.2.10 on 2025-11-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("devices", "0001_initial"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("SCREEN_SHARE", "Screen Share"),
                            ("REMOTE_CONTROL", "Remote Control"),
                            ("FILE_TRANSFER", "File Transfer"),
                            ("TERMINAL", "Terminal Access"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "session_token",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("requires_approval", models.BooleanField(default=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("duration_seconds", models.IntegerField(default=0)),
                ("max_duration_minutes", models.IntegerField(default=60)),
                ("is_recorded", models.BooleanField(default=True)),
                ("recording_url", models.URLField(blank=True)),
                (
                    "connection_method",
                    models.CharField(
                        choices=[
                            ("WEBRTC", "WebRTC"),
                            ("VNC", "VNC"),
                            ("RDP", "RDP"),
                            ("SSH", "SSH"),
                        ],
                        default="WEBRTC",
                        max_length=20,
                    ),
                ),
                ("connection_info", models.JSONField(blank=True, default=dict)),
                ("require_2fa", models.BooleanField(default=False)),
                ("ip_whitelist", models.JSONField(blank=True, default=list)),
                ("allowed_actions", models.JSONField(blank=True, default=list)),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_sessions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_sessions",
                        to="devices.device",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_sessions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_sessions_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_sessions",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "remote_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RemoteCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("command", models.TextField()),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("SHELL", "Shell Command"),
                            ("POWERSHELL", "PowerShell"),
                            ("SCRIPT", "Script Execution"),
                            ("SYSTEM", "System Command"),
                        ],
                        default="SHELL",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXECUTING", "Executing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(default=0)),
                ("stdout", models.TextField(blank=True)),
                ("stderr", models.TextField(blank=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("is_dangerous", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="remote_access.remotesession",
                    ),
                ),
            ],
            options={
                "db_table": "remote_commands",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECORDING", "Recording"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("DELETED", "Deleted"),
                        ],
                        default="RECORDING",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("duration_seconds", models.IntegerField(default=0)),
                (
                    "storage_provider",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local Storage"),
                            ("S3", "Amazon S3"),
                            ("AZURE_BLOB", "Azure Blob Storage"),
                            ("GCS", "Google Cloud Storage"),
                        ],
                        default="LOCAL",
                        max_length=50,
                    ),
                ),
                ("storage_url", models.URLField(blank=True)),
                ("video_format", models.CharField(default="mp4", max_length=20)),
                ("video_codec", models.CharField(blank=True, max_length=50)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                ("fps", models.IntegerField(default=30)),
                ("is_encrypted", models.BooleanField(default=True)),
                ("encryption_key_id", models.CharField(blank=True, max_length=255)),
                ("access_count", models.IntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("retention_days", models.IntegerField(default=90)),
                ("delete_at", models.DateTimeField(blank=True, null=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_error", models.TextField(blank=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to="remote_access.remotesession",
                    ),
                ),
            ],
            options={
                "db_table": "session_recordings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "status"],
                        name="session_rec_session_4615cc_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="session_rec_status_542d78_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CONNECT", "Connected"),
                            ("DISCONNECT", "Disconnected"),
                            ("COMMAND", "Command Executed"),
                            ("FILE_UPLOAD", "File Uploaded"),
                            ("FILE_DOWNLOAD", "File Downloaded"),
                            ("SCREEN_CAPTURE", "Screen Captured"),
                            ("CONTROL_GRANTED", "Control Granted"),
                            ("CONTROL_REVOKED", "Control Revoked"),
                            ("ERROR", "Error Occurred"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("action_data", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("was_successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="remote_access.remotesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_session_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "remote_session_logs",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="remote_sess_session_034e5b_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="remote_sess_action__5cfd45_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="remotesession",
            index=models.Index(
                fields=["session_token"], name="remote_sess_session_0d648a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remotesession",
            index=models.Index(
                fields=["technician", "-created_at"],
                name="remote_sess_technic_a472d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="remotesession",
            index=models.Index(
                fields=["device", "-created_at"], name="remote_sess_device__2e202c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remotesession",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="remote_sess_organiz_3b0ee0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="remotesession",
            index=models.Index(
                fields=["status", "-created_at"], name="remote_sess_status_0855ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remotecommand",
            index=models.Index(
                fields=["session", "created_at"], name="remote_comm_session_d4e268_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remotecommand",
            index=models.Index(
                fields=["status", "-created_at"], name="remote_comm_status_82d80e_idx"
            ),
        ),
    ]
