# Generated by Django 5.2.8 on 2025-11-23 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full System Scan"),
                            ("QUICK", "Quick Scan"),
                            ("TARGETED", "Targeted Scan"),
                            ("SCHEDULED", "Scheduled Scan"),
                        ],
                        default="FULL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("issues_found", models.IntegerField(default=0)),
                ("critical_issues", models.IntegerField(default=0)),
                ("high_issues", models.IntegerField(default=0)),
                ("medium_issues", models.IntegerField(default=0)),
                ("low_issues", models.IntegerField(default=0)),
                ("scan_areas", models.JSONField(default=list)),
                ("scan_results", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_scans",
                        to="devices.device",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_scans",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectedIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HARDWARE", "Hardware"),
                            ("SOFTWARE", "Software"),
                            ("NETWORK", "Network"),
                            ("SECURITY", "Security"),
                            ("PERFORMANCE", "Performance"),
                            ("STORAGE", "Storage"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("technical_details", models.JSONField(default=dict)),
                ("auto_fixable", models.BooleanField(default=False)),
                ("fix_applied", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_issues",
                        to="devices.device",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_issues",
                        to="organizations.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="ai_diagnostics.diagnosticscan",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("steps", models.JSONField(default=list)),
                (
                    "estimated_time",
                    models.IntegerField(help_text="Estimated time in minutes"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requires_restart", models.BooleanField(default=False)),
                ("requires_downtime", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("APPLIED", "Applied"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "success_rate",
                    models.FloatField(default=0.0, help_text="Success rate percentage"),
                ),
                ("times_applied", models.IntegerField(default=0)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="ai_diagnostics.detectedissue",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["risk_level", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoFixAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CLEANUP", "Disk Cleanup"),
                            ("UPDATE", "Software Update"),
                            ("RESTART_SERVICE", "Restart Service"),
                            ("CLEAR_CACHE", "Clear Cache"),
                            ("FIX_REGISTRY", "Fix Registry"),
                            ("OPTIMIZE", "System Optimization"),
                            ("SECURITY_PATCH", "Security Patch"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("rollback_possible", models.BooleanField(default=False)),
                ("rollback_data", models.JSONField(default=dict)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_fix_actions",
                        to="devices.device",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_fix_actions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_fix_actions",
                        to="ai_diagnostics.detectedissue",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_fix_actions",
                        to="ai_diagnostics.recommendation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical Alert"),
                            ("WARNING", "Warning"),
                            ("INFO", "Information"),
                            ("SUCCESS", "Success"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("DIAGNOSTIC_SCAN", "Diagnostic Scan"),
                            ("REAL_TIME_MONITORING", "Real-time Monitoring"),
                            ("THRESHOLD_VIOLATION", "Threshold Violation"),
                            ("SYSTEM_EVENT", "System Event"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_alerts",
                        to="devices.device",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="ai_diagnostics.detectedissue",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_alerts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="diagnosticscan",
            index=models.Index(
                fields=["device", "-created_at"], name="ai_diagnost_device__bda24c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticscan",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="ai_diagnost_organiz_f775ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticscan",
            index=models.Index(
                fields=["status", "-created_at"], name="ai_diagnost_status_6ce2e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectedissue",
            index=models.Index(
                fields=["device", "-created_at"], name="ai_diagnost_device__2a7991_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectedissue",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="ai_diagnost_organiz_ff9ab5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectedissue",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="ai_diagnost_severit_04f2cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="autofixaction",
            index=models.Index(
                fields=["device", "-created_at"], name="ai_diagnost_device__9f03cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autofixaction",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="ai_diagnost_organiz_061c7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="ai_diagnost_organiz_8c1a29_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["device", "status", "-created_at"],
                name="ai_diagnost_device__a3b572_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["alert_type", "-created_at"],
                name="ai_diagnost_alert_t_7fd0e4_idx",
            ),
        ),
    ]
