# Generated by Django 4.2.10 on 2025-11-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HARDWARE", "Hardware Issue"),
                            ("SOFTWARE", "Software Issue"),
                            ("NETWORK", "Network Issue"),
                            ("ACCESS", "Access/Permission Issue"),
                            ("EMAIL", "Email Issue"),
                            ("PRINTING", "Printing Issue"),
                            ("BACKUP", "Backup/Recovery"),
                            ("SECURITY", "Security Concern"),
                            ("REQUEST", "Service Request"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PENDING", "Pending User Response"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("response_sla_minutes", models.IntegerField(default=240)),
                ("resolution_sla_minutes", models.IntegerField(default=1440)),
                ("sla_breached", models.BooleanField(default=False)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="devices.device",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                ("is_internal", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("attachments", models.JSONField(blank=True, default=list)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ticket_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket", "created_at"],
                        name="ticket_mess_ticket__80bcb6_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ticket_mess_user_id_8fb3b2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketEscalation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_level",
                    models.CharField(
                        choices=[
                            ("L1", "Level 1 - Technician"),
                            ("L2", "Level 2 - Senior Technician"),
                            ("L3", "Level 3 - Technical Lead"),
                            ("L4", "Level 4 - Management"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "to_level",
                    models.CharField(
                        choices=[
                            ("L1", "Level 1 - Technician"),
                            ("L2", "Level 2 - Senior Technician"),
                            ("L3", "Level 3 - Technical Lead"),
                            ("L4", "Level 4 - Management"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SLA_BREACH", "SLA Breach"),
                            ("PRIORITY_INCREASE", "Priority Increased"),
                            ("CUSTOMER_REQUEST", "Customer Request"),
                            ("TECHNICAL_COMPLEXITY", "Technical Complexity"),
                            ("MANAGEMENT_REVIEW", "Management Review"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "escalated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_escalations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket", "-created_at"],
                        name="ticket_esca_ticket__638e51_idx",
                    ),
                    models.Index(
                        fields=["escalated_to", "is_active"],
                        name="ticket_esca_escalat_dd51e5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="tickets/attachments/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ticket_attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket", "-created_at"],
                        name="ticket_atta_ticket__11a317_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="tickets_organiz_271b60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["ticket_number"], name="tickets_ticket__4c9624_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["created_by", "-created_at"], name="tickets_created_b4a01a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assigned_to", "status"], name="tickets_assigne_fc2b2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["priority", "status"], name="tickets_priorit_552ea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["category", "-created_at"], name="tickets_categor_68457c_idx"
            ),
        ),
    ]
