# Generated by Django 4.2.10 on 2025-11-18 19:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("MICROSOFT_365", "Microsoft 365"),
                            ("GOOGLE_WORKSPACE", "Google Workspace"),
                            ("SLACK", "Slack"),
                            ("TEAMS", "Microsoft Teams"),
                            ("JIRA", "Jira"),
                            ("SALESFORCE", "Salesforce"),
                            ("ZENDESK", "Zendesk"),
                            ("OKTA", "Okta"),
                            ("AZURE_AD", "Azure Active Directory"),
                            ("CUSTOM", "Custom Integration"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ERROR", "Error"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("OAUTH2", "OAuth 2.0"),
                            ("API_KEY", "API Key"),
                            ("BASIC_AUTH", "Basic Authentication"),
                            ("BEARER_TOKEN", "Bearer Token"),
                        ],
                        default="OAUTH2",
                        max_length=20,
                    ),
                ),
                ("is_authenticated", models.BooleanField(default=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("sync_frequency_minutes", models.IntegerField(default=60)),
                ("total_sync_count", models.IntegerField(default=0)),
                ("failed_sync_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("token_type", models.CharField(default="Bearer", max_length=50)),
                ("scope", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "refresh_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("id_token", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_token",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "db_table": "oauth_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DomainHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("mx_records", models.JSONField(blank=True, default=list)),
                ("mx_status", models.CharField(default="UNKNOWN", max_length=20)),
                ("spf_record", models.TextField(blank=True)),
                (
                    "spf_status",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("MISSING", "Missing"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("dkim_records", models.JSONField(blank=True, default=list)),
                ("dkim_status", models.CharField(default="UNKNOWN", max_length=20)),
                ("dmarc_record", models.TextField(blank=True)),
                ("dmarc_status", models.CharField(default="UNKNOWN", max_length=20)),
                ("ssl_valid", models.BooleanField(default=False)),
                ("ssl_expiry_date", models.DateTimeField(blank=True, null=True)),
                ("ssl_issuer", models.CharField(blank=True, max_length=255)),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("blacklist_sources", models.JSONField(blank=True, default=list)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("last_checked_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_health_checks",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "domain_health",
                "ordering": ["-last_checked_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("SYNC", "Sync Operation"),
                            ("AUTH", "Authentication"),
                            ("WEBHOOK", "Webhook"),
                            ("API_CALL", "API Call"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(default=0)),
                ("error_trace", models.TextField(blank=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "db_table": "integration_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["integration", "-created_at"],
                        name="integration_integra_9c0fc0_idx",
                    ),
                    models.Index(
                        fields=["log_type", "-created_at"],
                        name="integration_log_typ_461903_idx",
                    ),
                    models.Index(
                        fields=["level", "-created_at"],
                        name="integration_level_a3b4be_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["organization", "status"], name="integration_organiz_76b850_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["integration_type", "status"],
                name="integration_integra_49ddd6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integration",
            unique_together={("organization", "integration_type", "name")},
        ),
        migrations.AddIndex(
            model_name="domainhealth",
            index=models.Index(
                fields=["organization", "-last_checked_at"],
                name="domain_heal_organiz_fc308c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="domainhealth",
            index=models.Index(
                fields=["domain", "-last_checked_at"],
                name="domain_heal_domain_ee141b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="domainhealth",
            index=models.Index(
                fields=["status", "-last_checked_at"],
                name="domain_heal_status_463801_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="domainhealth",
            unique_together={("organization", "domain")},
        ),
    ]
