# Generated by Django 5.2.8 on 2025-11-23 21:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AntivirusStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("antivirus_name", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                ("definitions_date", models.DateField(blank=True, null=True)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("SCANNING", "Scanning"),
                            ("THREAT_FOUND", "Threat Found"),
                            ("SCAN_FAILED", "Scan Failed"),
                        ],
                        default="IDLE",
                        max_length=20,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antivirus_statuses",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "antivirus_statuses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-created_at"],
                        name="antivirus_s_device__389174_idx",
                    ),
                    models.Index(
                        fields=["antivirus_name", "-created_at"],
                        name="antivirus_s_antivir_98a2c5_idx",
                    ),
                    models.Index(
                        fields=["enabled"], name="antivirus_s_enabled_dd971e_idx"
                    ),
                    models.Index(
                        fields=["scan_status", "-created_at"],
                        name="antivirus_s_scan_st_240b35_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_name", models.CharField(max_length=255)),
                (
                    "strength_score",
                    models.IntegerField(
                        help_text="Password strength score from 0 to 100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_reused",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the password is reused across services",
                    ),
                ),
                ("last_changed", models.DateField(blank=True, null=True)),
                (
                    "days_since_change",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days since password was last changed",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "compliant",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the password meets compliance requirements",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_audits",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="password_au_user_id_b1131e_idx",
                    ),
                    models.Index(
                        fields=["service_name"], name="password_au_service_bfb95f_idx"
                    ),
                    models.Index(
                        fields=["is_reused"], name="password_au_is_reus_437e2e_idx"
                    ),
                    models.Index(
                        fields=["compliant"], name="password_au_complia_ec1fb4_idx"
                    ),
                    models.Index(
                        fields=["strength_score"], name="password_au_strengt_aefab2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatchStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patch_type",
                    models.CharField(
                        choices=[
                            ("OS_UPDATE", "Operating System Update"),
                            ("SECURITY_PATCH", "Security Patch"),
                            ("DRIVER_UPDATE", "Driver Update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("patch_name", models.CharField(max_length=255)),
                ("current_version", models.CharField(blank=True, max_length=100)),
                ("available_version", models.CharField(blank=True, max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                ("release_date", models.DateField()),
                ("installed", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patches",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "patch_statuses",
                "ordering": ["-release_date", "-severity"],
                "indexes": [
                    models.Index(
                        fields=["device", "-release_date"],
                        name="patch_statu_device__05da19_idx",
                    ),
                    models.Index(
                        fields=["patch_type", "-release_date"],
                        name="patch_statu_patch_t_fdedbe_idx",
                    ),
                    models.Index(
                        fields=["severity", "-release_date"],
                        name="patch_statu_severit_053a6e_idx",
                    ),
                    models.Index(
                        fields=["installed"], name="patch_statu_install_621219_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ThreatDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "threat_type",
                    models.CharField(
                        choices=[
                            ("MALWARE", "Malware"),
                            ("UNAUTHORIZED_ACCESS", "Unauthorized Access"),
                            ("RISKY_APP", "Risky Application"),
                            ("PHISHING", "Phishing"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DETECTED", "Detected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="DETECTED",
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("detected_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threats",
                        to="devices.device",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threats",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "threat_detections",
                "ordering": ["-detected_at", "-severity"],
                "indexes": [
                    models.Index(
                        fields=["device", "-detected_at"],
                        name="threat_dete_device__1d9a5d_idx",
                    ),
                    models.Index(
                        fields=["organization", "-detected_at"],
                        name="threat_dete_organiz_b5122b_idx",
                    ),
                    models.Index(
                        fields=["threat_type", "-detected_at"],
                        name="threat_dete_threat__2d5fa8_idx",
                    ),
                    models.Index(
                        fields=["severity", "-detected_at"],
                        name="threat_dete_severit_189d90_idx",
                    ),
                    models.Index(
                        fields=["status", "-detected_at"],
                        name="threat_dete_status_a0bc1e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WiFiAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ssid", models.CharField(max_length=255)),
                (
                    "signal_strength",
                    models.IntegerField(
                        help_text="WiFi signal strength in dBm",
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(0),
                        ],
                    ),
                ),
                (
                    "channel",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(165),
                        ]
                    ),
                ),
                ("frequency", models.IntegerField(help_text="Frequency in MHz")),
                (
                    "download_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Download speed in Mbps",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "upload_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Upload speed in Mbps",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "latency",
                    models.IntegerField(
                        blank=True, help_text="Latency in milliseconds", null=True
                    ),
                ),
                (
                    "packet_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Packet loss percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("interference_detected", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wifi_analyses",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "wifi_analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-created_at"],
                        name="wifi_analys_device__c40502_idx",
                    ),
                    models.Index(
                        fields=["ssid", "-created_at"],
                        name="wifi_analys_ssid_6124f3_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="wifi_analys_created_e446e6_idx"
                    ),
                ],
            },
        ),
    ]
