# Generated by Django 4.2.10 on 2025-11-18 19:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                (
                    "device_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("serial_number", models.CharField(blank=True, max_length=255)),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("WINDOWS", "Windows"),
                            ("MACOS", "macOS"),
                            ("LINUX", "Linux"),
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("os_version", models.CharField(blank=True, max_length=100)),
                ("os_build", models.CharField(blank=True, max_length=100)),
                ("cpu_model", models.CharField(blank=True, max_length=255)),
                ("cpu_cores", models.IntegerField(blank=True, null=True)),
                (
                    "ram_total_gb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "disk_total_gb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("DESKTOP", "Desktop"),
                            ("LAPTOP", "Laptop"),
                            ("TABLET", "Tablet"),
                            ("PHONE", "Phone"),
                            ("SERVER", "Server"),
                            ("OTHER", "Other"),
                        ],
                        default="DESKTOP",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("MAINTENANCE", "Maintenance"),
                            ("DECOMMISSIONED", "Decommissioned"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_managed", models.BooleanField(default=True)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("is_compliant", models.BooleanField(default=True)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("agent_installed_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("api_key_hash", models.CharField(blank=True, max_length=255)),
                ("registration_token", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "devices",
                "ordering": ["-last_seen_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "avg_cpu_usage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "avg_ram_usage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "avg_disk_usage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "peak_cpu_usage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "peak_ram_usage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "peak_disk_usage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_uptime_seconds", models.BigIntegerField(default=0)),
                (
                    "uptime_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("health_checks_count", models.IntegerField(default=0)),
                ("healthy_count", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                ("critical_count", models.IntegerField(default=0)),
                (
                    "total_upload_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_download_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "device_metrics",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["device", "metric_type", "-period_start"],
                        name="device_metr_device__8a3ae7_idx",
                    )
                ],
                "unique_together": {("device", "metric_type", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="DeviceHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "cpu_usage_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cpu_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ram_used_gb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ram_usage_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "disk_used_gb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "disk_usage_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "battery_percent",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("battery_is_charging", models.BooleanField(default=False)),
                (
                    "battery_estimated_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "network_upload_mbps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "network_download_mbps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("network_latency_ms", models.IntegerField(blank=True, null=True)),
                ("uptime_seconds", models.BigIntegerField(blank=True, null=True)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "device_health",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-created_at"],
                        name="device_heal_device__11d0c4_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="device_heal_status_1a34be_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["organization", "is_active"], name="devices_organiz_a7b347_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["device_id"], name="devices_device__c4b5e4_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["user", "is_active"], name="devices_user_id_095ba7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["status", "-last_seen_at"], name="devices_status_2b4717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["os_type"], name="devices_os_type_e36346_idx"),
        ),
    ]
