# Generated by Django 5.2.8 on 2025-11-23 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                            ("PERMISSION_GRANT", "Permission Grant"),
                            ("PERMISSION_REVOKE", "Permission Revoke"),
                            ("CONFIG_CHANGE", "Configuration Change"),
                            ("DEVICE_ACTION", "Device Action"),
                            ("REMOTE_SESSION", "Remote Session"),
                            ("RESET_PASSWORD", "Reset Password"),
                            ("API_CALL", "API Call"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of resource affected (e.g., User, Device, Organization)",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the specific resource affected",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional details about the activity in JSON format",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which the action was performed",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string of the client",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "db_table": "activity_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activity_lo_user_id_b8c999_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="activity_lo_organiz_07aac4_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="activity_lo_action_78df1b_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "-created_at"],
                        name="activity_lo_resourc_c87679_idx",
                    ),
                    models.Index(
                        fields=["organization", "action", "-created_at"],
                        name="activity_lo_organiz_91b3c6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("USER_CREATED", "User Created"),
                            ("USER_UPDATED", "User Updated"),
                            ("USER_DELETED", "User Deleted"),
                            ("USER_ACTIVATED", "User Activated"),
                            ("USER_DEACTIVATED", "User Deactivated"),
                            ("DEVICE_ADDED", "Device Added"),
                            ("DEVICE_REMOVED", "Device Removed"),
                            ("DEVICE_UPDATED", "Device Updated"),
                            ("PERMISSION_CHANGED", "Permission Changed"),
                            ("ROLE_ASSIGNED", "Role Assigned"),
                            ("ROLE_REVOKED", "Role Revoked"),
                            ("POLICY_CREATED", "Policy Created"),
                            ("POLICY_UPDATED", "Policy Updated"),
                            ("POLICY_DELETED", "Policy Deleted"),
                            ("SECURITY_EVENT", "Security Event"),
                            ("CONFIGURATION_CHANGED", "Configuration Changed"),
                            ("API_KEY_CREATED", "API Key Created"),
                            ("API_KEY_REVOKED", "API Key Revoked"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Description of the action taken", max_length=255
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="State of the resource before the change",
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="State of the resource after the change",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Flag for sensitive operations (e.g., password changes)",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_records",
                        to="organizations.organization",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_records_targeting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Record",
                "verbose_name_plural": "Audit Records",
                "db_table": "audit_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="audit_recor_organiz_1aab71_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="audit_recor_event_t_6b1436_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_recor_actor_i_398817_idx",
                    ),
                    models.Index(
                        fields=["target_user", "-created_at"],
                        name="audit_recor_target__cd25f4_idx",
                    ),
                    models.Index(
                        fields=["is_sensitive", "-created_at"],
                        name="audit_recor_is_sens_4db631_idx",
                    ),
                    models.Index(
                        fields=["organization", "event_type", "-created_at"],
                        name="audit_recor_organiz_a1f865_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the custom role", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the role and its responsibilities",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="Array of permission strings/identifiers",
                    ),
                ),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False,
                        help_text="Flag to indicate if this is a system-defined role",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_roles_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_roles",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Role",
                "verbose_name_plural": "Custom Roles",
                "db_table": "custom_roles",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "name"],
                        name="custom_role_organiz_585ad8_idx",
                    ),
                    models.Index(
                        fields=["is_system_role"], name="custom_role_is_syst_8af0ad_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="custom_role_created_54c828_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "name"), name="unique_role_per_org"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("PASSWORD", "Password Policy"),
                            ("MFA", "Multi-Factor Authentication"),
                            ("SESSION", "Session Management"),
                            ("DEVICE", "Device Policy"),
                            ("SECURITY", "Security Policy"),
                            ("DATA_RETENTION", "Data Retention"),
                            ("ACCESS_CONTROL", "Access Control"),
                            ("API", "API Policy"),
                            ("AUDIT", "Audit Policy"),
                            ("ENCRYPTION", "Encryption Policy"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "policy_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration parameters for the policy",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this policy is currently enabled",
                    ),
                ),
                (
                    "enforced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the policy was last enforced",
                        null=True,
                    ),
                ),
                (
                    "enforced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enforced_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Policy",
                "verbose_name_plural": "Organization Policies",
                "db_table": "organization_policies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "policy_type"],
                        name="organizatio_organiz_0578bf_idx",
                    ),
                    models.Index(
                        fields=["enabled", "-created_at"],
                        name="organizatio_enabled_11714f_idx",
                    ),
                    models.Index(
                        fields=["organization", "enabled"],
                        name="organizatio_organiz_8f8abc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "policy_type"),
                        name="unique_policy_type_per_org",
                    )
                ],
            },
        ),
    ]
