# Generated by Django 4.2.10 on 2025-11-18 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt", models.TextField()),
                ("system_prompt", models.TextField(blank=True)),
                ("model", models.CharField(max_length=100)),
                (
                    "temperature",
                    models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
                ),
                ("max_tokens", models.IntegerField(default=500)),
                ("response_text", models.TextField()),
                ("finish_reason", models.CharField(blank=True, max_length=50)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("response_time_ms", models.IntegerField(default=0)),
                ("api_status_code", models.IntegerField(default=200)),
                ("detected_intent", models.CharField(blank=True, max_length=100)),
                (
                    "detected_sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEUTRAL", "Neutral"),
                            ("NEGATIVE", "Negative"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("action_triggered", models.CharField(blank=True, max_length=100)),
                ("action_params", models.JSONField(blank=True, default=dict)),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("user_feedback", models.TextField(blank=True)),
                ("needs_human_review", models.BooleanField(default=False)),
                ("error_occurred", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("error_trace", models.TextField(blank=True)),
            ],
            options={
                "db_table": "ai_responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("AI", "AI Assistant"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("model", models.CharField(blank=True, max_length=100)),
                ("tokens_used", models.IntegerField(default=0)),
                ("response_time_ms", models.IntegerField(default=0)),
                ("intent", models.CharField(blank=True, max_length=100)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("references", models.JSONField(blank=True, default=list)),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("feedback_text", models.TextField(blank=True)),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Support"),
                            ("DEVICE", "Device Issue"),
                            ("TICKET", "Ticket Related"),
                            ("TROUBLESHOOTING", "Troubleshooting"),
                            ("ONBOARDING", "User Onboarding"),
                        ],
                        default="GENERAL",
                        max_length=50,
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                ("ai_response_count", models.IntegerField(default=0)),
                ("avg_response_time_ms", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "chat_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TROUBLESHOOTING", "Troubleshooting"),
                            ("HOW_TO", "How To"),
                            ("FAQ", "FAQ"),
                            ("BEST_PRACTICES", "Best Practices"),
                            ("POLICY", "Policy"),
                            ("TECHNICAL", "Technical Documentation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_public", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("view_count", models.IntegerField(default=0)),
                ("helpful_count", models.IntegerField(default=0)),
                ("not_helpful_count", models.IntegerField(default=0)),
                ("version", models.IntegerField(default=1)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "knowledge_base",
                "ordering": ["-created_at"],
            },
        ),
    ]
