# Generated by Django 4.2.10 on 2025-11-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("ai_engine", "0001_initial"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kb_articles_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_base",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="related_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_sessions",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="related_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_sessions",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ai_engine.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="chat_message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_response_details",
                to="ai_engine.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(
                fields=["organization", "is_active"],
                name="knowledge_b_organiz_7c36c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(
                fields=["category", "is_active"], name="knowledge_b_categor_2c991d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(
                fields=["is_public", "is_active"], name="knowledge_b_is_publ_038512_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-created_at"], name="chat_sessio_user_id_c65971_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="chat_sessio_organiz_88ca34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["status", "-created_at"], name="chat_sessio_status_4e91f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chat_messag_session_597c4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["role", "-created_at"], name="chat_messag_role_c524cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_response_user_id_92cb04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(
                fields=["model", "-created_at"], name="ai_response_model_8244e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(
                fields=["error_occurred", "-created_at"],
                name="ai_response_error_o_999c3b_idx",
            ),
        ),
    ]
